### ISSUE TITLE
ucf-crime_regular_features-2048dim.training.pickle file

### ISSUE THREAD

**Issue by mmi-w-1400** [louisYen/S3R#1]
Hello, thank you for your excellent work. I want ask you, what is` ucf-crime_regular_features-2048dim.training.pickle` file? how did you to make `ucf-crime_regular_features-2048dim.training.pickle` file?

**Comment by louisYen** [comment]
Hi, thank you for your attention.  The `ucf-crime_regular_features-2048dim.training.pickle` file collects all normal (regular) training features of the UCF-Crime dataset, where we use the features from this work (https://github.com/tianyu0207/RTFM). The generation steps of `ucf-crime_regular_features-2048dim.training.pickle` file are:
1. Download UCF-Crime features from this work (https://github.com/tianyu0207/RTFM)
2. Collect all normal features 
3. Sample 32 snippets for each feature
4. Dimension of sampled features : (T', N, C), where T', N, and C denote the number of sampled snippets, number of croppings, and channels, respectively.
5. Put all sampled features into a dictionary
6. Save this dictionary with the filename of `ucf-crime_regular_features-2048dim.training.pickle` using the python pickle library.

**Comment by mmi-w-1400** [comment]
Thanks for answer. Ummm, I check dimensions features and there aren't match, for example for  _Normal_Videos002_x264_  dimension in `ucf-crime_regular_features-2048dim.training.pickle` is (10, 32, 2048), but dimension of _Normal_Videos002_x264_i3d.npy_ from this work  (https://github.com/tianyu0207/RTFM) is (104, 10, 2048).

**Comment by louisYen** [comment]
Hi, thank you for your check. The dimension of Normal_Videos002_x264_i3d.npy is (T=original_number_of_snippets, N=num_croppings, C=channels) (e.g.,  T=104, N=10, C=2048))
Next, the authors of RTFM sample 32 snippets for training.
In our saving format, we save each feature in the shape of (N=num_croppings, T'=number_of_sampled_snippet, C=channels). I have updated the description of the generation step. Thank you.

**Comment by mmi-w-1400** [comment]
Thanks

**Comment by louisYen** [comment]
My pleasure :)

**Comment by coranholmes** [comment]
> Hi, thank you for your check. The dimension of Normal_Videos002_x264_i3d.npy is (T=original_number_of_snippets, N=num_croppings, C=channels) (e.g., T=104, N=10, C=2048)) Next, the authors of RTFM sample 32 snippets for training. In our saving format, we save each feature in the shape of (N=num_croppings, T'=number_of_sampled_snippet, C=channels). I have updated the description of the generation step. Thank you.

I understand your logic here but still is it possible for you to share your codes to generate the pickle file so we can adapt it conveniently on customized dataset? Thank you very much!

**Comment by DNGC112** [comment]
> 

It's very presumptuous to bother you, have you succeeded in generating the pickle file, I am facing some difficulties in generating the pickle for my own dataset, can you share it if possible. Thank you very much!
